# SPDX-FileCopyrightText: 2026 UltimateTerminal contributors
# SPDX-License-Identifier: GPL-3.0-or-later

version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      gradle:
        patterns: ["*"]
    commit-message:
      prefix: build

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
    commit-message:
      prefix: ci
